### PR TITLE
Change Fixnum test to Integer

### LINKED ISSUE #61: Ruby 4 Deprecation Warning - Fixnum
Upgraded to Ruby 2.5.1, seeing this deprecation warning
```
/Users/randallreedjr/.rvm/gems/ruby-2.5.1@screenslate/gems/acts_as_indexed-0.8.3/lib/acts_as_indexed/class_methods.rb:177: warning: constant ::Fixnum is deprecated
```
As of Ruby 2.4.0, [Fixnum and Bignum are unified into Integer](https://www.ruby-lang.org/en/news/2016/12/25/ruby-2-4-0-released/).

### PR DESCRIPTION
**Pull request by yez**
Fixes #61

When updating to Ruby 2.5, Fixnum has been deprecated and eventually
removed.

Some formatting was also off and I fixed that.

I also suggest outside of this PR to add more versions to .travis.yml

### CODE REVIEW

**Comment by yez** [comment]
Build failures seem unrelated to this change.

**Comment by randallreedjr** [comment]
@yez Thanks for the fix!

**Comment by yez** [comment]
@randallreedjr happy to contribute. I'm not able to restart that Travis build so let me know if these failures are legitimate and I can help more.

**Comment by ryankopf** [comment]
Going to merge this next week, trying to see if I can get the workflow working and test this again before merging, but the change seems trivial.

**Comment by ryankopf** [comment]
Update: Going to merge after I merge my test-workflow branch to get testing and Github actions going.

**Pull request merged**
